server:
  port: ${SERVER_PORT:8082}
  address: ${SERVER_ADDRESS:localhost}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Centero-Netzero
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:org.h2.Driver} # default driver class name is org.h2.Driver
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    hikari:
      minimum-idle: ${HIKARI_MINIMUM_IDLE:5} # minimum number of idle connections that HikariCP tries to maintain in the pool
      max-lifetime: ${HIKARI_MAX_LIFETIME:240000} # maximum lifetime of a connection in the pool
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:10} # maximum number of connections in the pool
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:100000} # maximum amount of time a connection is allowed to sit idle in the pool
  sql:
    init:
      mode: ${SQL_INIT_MODE} # run schema.sql and data.sql for test in h2, local profile only
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
   config: classpath:logback-spring.xml

# mybatis config
mybatis:
  type-handlers-package: kr.centero.core.common.typehandler # enum type handler package
  type-aliases-package: kr.centero.netzero.**.model;kr.centero.core.**.model
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    default-statement-timeout: 5
    jdbc-type-for-null: NULL
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

# token config
token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
  expiration:
    access: ${TOKEN_EXPIRATION_ACCESS:30m} # d(day), h(hour), m(minute)
    refresh: ${TOKEN_EXPIRATION_REFRESH:1d} # d(day), h(hour), m(minute)

# cookie config
cookie:
  access-token:
    name: ${COOKIE_NAME:accessToken}
    duration: ${COOKIE_DURATION:1h} # d(day), h(hour), m(minute)
    domain: ${COOKIE_DOMAIN:localhost}
    secure: ${COOKIE_SECURE:false}
    same-site: ${COOKIE_SAME_SITE:None}

# feign config
feign:
  client:
    config:
      default:
        connectTimeout: ${CONNECT_TIMEOUT:10000} # 10 seconds
        readTimeout: ${READ_TIMEOUT:10000} # 10 seconds

# api server endpoint
api-server:
  ghg-url: http://ghg-api.centero.kr:8081
  netzero-url: http://netzero-api.centero.kr:8082
  common-url: http://common-api.centero.kr:8080
