### 로그인
POST http://localhost:8081/api/ghg/v1/auth/signin
Content-Type: application/json

{
  "username": "Lee",
  "password": "pwd1"
}

> {% //response handler
client.global.set("accessToken", response.body.data.accessToken);
client.log(client.global.get("accessToken"));
%}


### 사용자 전체 검색
GET http://localhost:8081/api/ghg/v1/users
Authorization: Bearer {{accessToken}}

### 사용자 검색 조회 [GET]
GET http://localhost:8081/api/ghg/v1/users/query?username=Lee&role=ADMIN
Authorization: Bearer {{accessToken}}

### 사용자 검색 조회 [POST]
POST http://localhost:8081/api/ghg/v1/users/query
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "Lee",
  "role": "USER"
}

### 사용자 페이징 검색 조회 [GET] pageNo 1, pageSize 5
GET http://localhost:8081/api/ghg/v1/users/pages?role=USER&pageNo=1&pageSize=5
Authorization: Bearer {{accessToken}}

### 사용자 페이징 검색 조회 [GET] pageNo 2, pageSize 5
GET http://localhost:8081/api/ghg/v1/users/pages?role=USER&pageNo=2&pageSize=5
Authorization: Bearer {{accessToken}}

### 사용자 페이징 검색 조회 [POST] pageNo 1, pageSize 5
POST http://localhost:8081/api/ghg/v1/users/pages
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId" : "",
  "username" : "",
  "email": "",
  "role" : "USER",
  "pageNo" : "1",
  "pageSize" : "5"
}

### 사용자 페이징 검색 조회 [POST] pageNo 2, pageSize 5
POST http://localhost:8081/api/ghg/v1/users/pages
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId" : "",
  "username" : "",
  "email": "",
  "role" : "USER",
  "pageNo" : "2",
  "pageSize" : "5"
}


### 사용자 정보 수정
PUT http://localhost:8081/api/ghg/v1/users/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId" : "2",
  "username" : "king Kong",
  "email": "kingkong@naver.com"
}


