### 로그인
POST http://localhost:8081/api/ghg/v1/auth/signin
Content-Type: application/json

{
  "username": "Lee",
  "password": "pwd1"
}

> {% //response handler
  client.global.set("accessToken", response.body.data.accessToken);
  client.log(client.global.get("accessToken"));
%}

### 공통코드 조회
POST http://localhost:8081/api/ghg/v1/admin/codes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "searchText": "abc"
}

###
#{
#  "searchText": "abc",
#  "pCodeCd": [
#    "여기에 코드1을 입력하세요",
#    "여기에 코드2를 입력하세요"
#  ],
#  "period": [
#    "여기에 시작 기간을 입력하세요",
#    "여기에 종료 기간을 입력하세요"
#  ],
#  "useYn": "여기에 사용 여부를 입력하세요 (예: Y 또는 N)"
#}
###
