SERVER_PORT: 8080
# Current Active Profile
spring:
  config:
    activate:
      on-profile: dev
# Database Configuration
DRIVER_CLASS_NAME: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # com.mysql.cj.jdbc.Driver
DATABASE_URL: jdbc:log4jdbc:mysql://unionplace.iptime.org:9308/centero
DATABASE_USERNAME: centero_dev
DATABASE_PASSWORD: Union2030!
HIKARI_MINIMUM_IDLE: 5
HIKARI_MAX_LIFETIME: 240000
HIKARI_MAXIMUM_POOL_SIZE: 10
HIKARI_IDLE_TIMEOUT: 100000
SQL_INIT_MODE: never
