SERVER_PORT: 8080
SERVER_ADDRESS: common-api.centero.kr
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
# Current Active Profile
  config:
    activate:
      on-profile: h2
# Database Configuration
DRIVER_CLASS_NAME: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
DATABASE_URL: jdbc:log4jdbc:h2:mem:testdb
DATABASE_USERNAME: sa
DATABASE_PASSWORD:
HIKARI_MINIMUM_IDLE: 5
HIKARI_MAX_LIFETIME: 240000
HIKARI_MAXIMUM_POOL_SIZE: 10
HIKARI_IDLE_TIMEOUT: 100000
SQL_INIT_MODE: always
# Redis Configuration
REDIS_HOST: unionplace.iptime.org
REDIS_PORT: 9679
# JWT Configuration
TOKEN_SIGNING_KEY: E147F935D2219326321BFC7B2CE4BCCD8324E2FCA4D03841E5EE8210DA788BAB
TOKEN_EXPIRATION_ACCESS: 30m
TOKEN_EXPIRATION_REFRESH: 1d
# Cookie Configuration
COOKIE_NAME: accessToken
COOKIE_DURATION: 7d
COOKIE_DOMAIN: centero.kr
COOKIE_SECURE: false
COOKIE_SAME_SITE: Lax
# OpenFeign Configuration
CONNECT_TIMEOUT: 10000 # 10s
READ_TIMEOUT: 10000 # 10s
