SERVER_PORT: 8080
# Current Active Profile
spring:
  config:
    activate:
      on-profile: local
# Database Configuration
DRIVER_CLASS_NAME: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # com.mysql.cj.jdbc.Driver
DATABASE_URL: jdbc:log4jdbc:mysql://localhost:3306/centero_common?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
DATABASE_USERNAME: root
DATABASE_PASSWORD: pwd1234!
HIKARI_MINIMUM_IDLE: 5
HIKARI_MAX_LIFETIME: 240000
HIKARI_MAXIMUM_POOL_SIZE: 10
HIKARI_IDLE_TIMEOUT: 100000

token:
  signing:
    key: e147f935d2219326321bfc7b2ce4bccd8324e2fca4d03841e5ee8210da788bab
  expiration:
    access: 10m # w(week), d(day), h(hour), m(minute), s(second)
    refresh: 1h # w(week), d(day), h(hour), m(minute), s(second)